dotfiles:
  - d_applications
  - d_aria2
  - d_cargo
  - d_ccache
  - d_containers
  - d_emacs
  - d_fcitx5
  - d_fish
  - d_flatpak
  - d_gdb
  - d_git
  - d_konsole
  - d_libvirt
  - d_lxc
  - d_mpv
  - d_peerbanhelper
  - d_proxychains
  - d_python
  - d_qbittorrent
  - d_samba
  - d_sccache
  - f_screen
  - d_ssh
  - d_systemd_develop
  - d_systemd-environment
  - d_systemd-tmpfiles
  - d_tmux
  - f_user-dirs
  - d_v2core
  - f_wget
  - d_workflow-config
