[project]
org = "{{@@ projects.source_info['piglit'].org @@}}"
build_system = "cmake"
generator = "Ninja Multi-Config"
toolchain = "clang"
build_dir = "{{work.dir}}/_build/{{branch.slug}}"
install_dir = "{{work.dir}}/_build/{{branch.slug}}"

[repos.main]
path = "{{@@ projects.root_dir @@}}/{{project.org}}/{{project.name}}"
main_branch = "main"
[repos.main.remotes]
origin = "https://gitlab.freedesktop.org/mesa/piglit.git"
