# -*- mode: gitconfig; coding: utf-8; indent-tabs-mode: nil; -*-
[alias]
        # Custom alias to run the git-stack tool for managing stacked branches
        stack = !{{@@ xdg_bin_home @@}}/wits-stack
        # Custom alias to run the git-review tool for reviewing forge's MRs
        review = !{{@@ xdg_bin_home @@}}/wits-review
        # Custom alias to run the git-transcrypt tool for transparent encryption of files
        transcrypt = !{{@@ xdg_bin_home @@}}/wits-transcrypt
