# -*- mode: gitconfig; coding: utf-8; indent-tabs-mode: nil; -*-
[user]
        # Only use configuration for user identity, ignore environment variables
        useConfigOnly = true

[include]
        # Include personal dispatch configuration
        path = personal_dispatch.conf
        # Conditionally include profile-specific dispatch configuration
        path = {{@@ profile @@}}_dispatch.conf
        # Include profile-specific transcrypt configuration
        path = {{@@ profile @@}}_transcrypt.conf
