# Miniflux configuration file
# https://miniflux.app/docs/configuration.html

# Database connection
DATABASE_URL=user={{@@ vps.apps.rss.name @@}} password={{@@ vps_apps.rss.password @@}} dbname={{@@ vps.apps.rss.name @@}} sslmode=disable

# Base url
BASE_URL=https://{{@@ vps.apps.rss.domain @@}}

# Run database migrations automatically
RUN_MIGRATIONS=1

# Create initial admin user from file (dotdrop will deploy the secret file)
CREATE_ADMIN=1
ADMIN_USERNAME={{@@ vps.apps.rss.name @@}}
ADMIN_PASSWORD_FILE={{@@ vps.apps.rss.home_dir @@}}/miniflux_admin_password

# Listen address
LISTEN_ADDR={{@@ vps.apps.rss.bind @@}}:{{@@ vps.apps.rss.port @@}}

# Worker pool size
WORKER_POOL_SIZE=10

# Polling frequency
POLLING_FREQUENCY=60

# Metrics
METRICS_COLLECTOR=1
METRICS_ALLOWED_NETWORKS={{@@ vps.apps.rss.bind @@}}/8
