[Service]
User=miniflux
Group=miniflux
# EnvironmentFile= (empty) clears the package default (/etc/miniflux.conf)
EnvironmentFile=
EnvironmentFile={{@@ vps.apps.rss.home_dir @@}}/miniflux.conf
# ExecStart= (empty) clears the package default before setting ours
ExecStart=
ExecStart=/usr/bin/miniflux -config-file {{@@ vps.apps.rss.home_dir @@}}/miniflux.conf
