#!/usr/bin/env bash
export HOOK_NAME=pre-push
source $(git rev-parse --git-common-dir)/hooks/common.sh
export push_command=$(ps -ocommand= -p $PPID)
export REMOTE_REF=$1

HOOKDIR="$GIT_COMMON_DIR/hooks/$HOOK_NAME.d"
if [[ -d "$HOOKDIR" ]]; then
  set -o pipefail
  find -L "$HOOKDIR" -maxdepth 1 -type f -print0 |xargs -0 -I @ bash -c 'eval @'
fi

find-program git-lfs
git lfs pre-push "$@"
