#!/usr/bin/env bash
export HOOK_NAME=pre-commit
source $(git rev-parse --git-common-dir)/hooks/common.sh

$GIT_COMMON_DIR/hooks/pre-commit.d/warn-protected.sh
find-program clang-format
find-program perl

commands=(encoding.pl format.sh)
for subcommand in ${commands[@]}; do
    "$GIT_COMMON_DIR/hooks/pre-commit.d/$subcommand"
    check-result $?
done
