#!/usr/bin/env bash
export HOOK_NAME=pre-push
source $(git rev-parse --git-common-dir)/hooks/common.sh
push_command=$(ps -ocommand= -p $PPID)

export REMOTE_REF=$1
$GIT_COMMON_DIR/hooks/pre-push.d/warn-protected.sh
check-result $?
$GIT_COMMON_DIR/hooks/pre-push.d/warn-force-push.sh
check-result $?

find-program git-lfs
git lfs pre-push "$@"
